In [1]:
import pandas as pd
import numpy as np
import os
#import warnings
#warnings.filterwarnings('ignore')
from datetime import date
from datetime import datetime
import dateutil
from pandas import *
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [2]:
csv_files = os.chdir('C:\\Users\\HP\\Desktop\\PHD Hackathon\\Data Science\\PHD Models\\Weather_Features')
weather_features = pd.read_csv('weatherData_full.csv', encoding='latin 1')
holidays_features = pd.read_csv('holidays_features.csv')
economic_features = pd.read_csv('economic_features.csv')
womenClothing_sales = pd.read_csv('womenClothing_sales.csv')

In [3]:
train_data = weather_features.merge(holidays_features, left_on=['Year', 'Month'], right_on=['Year', 'Month'], how='inner')
train_data = train_data.merge(economic_features, left_on=['Year', 'Month'], right_on=['Year', 'Month'], how='inner')
train_data = train_data.merge(womenClothing_sales, left_on=['Year', 'Month'], right_on=['Year', 'Month'], how='inner')

In [4]:
train_data.head()

,Year,Month,Temp high (°C)min,Temp high (°C)max,Temp high (°C)mean,Temp high (°C)var,Temp avg (°C)min,Temp avg (°C)max,Temp avg (°C)mean,Temp avg (°C)var,...,AdvertisingExpenses (in Thousand Dollars),Cotton Monthly Price - US cents per Pound(lbs),Change(in%),Average upland planted(million acres),Average upland harvested(million acres),yieldperharvested acre,Production (in 480-lb netweright in million bales),Mill use (in 480-lb netweright in million bales),Exports,WomenClothing_Sales
0,2009,1,-9.0,8.0,0.741935,16.664516,-11.0,5.0,-2.096774,13.956989,...,137.0,57.70,4.02,9.296,7.559,799,12.589,4.17,11.550,1755.0
1,2009,10,7.0,23.0,16.258065,20.064516,6.0,19.0,12.870968,14.582796,...,0.0,66.82,4.29,8.989,7.586,799,12.631,3.37,10.000,2579.0
2,2009,11,10.0,21.0,13.733333,8.202299,7.0,16.0,10.800000,5.889655,...,0.0,71.78,7.42,8.989,7.586,767,12.129,3.37,9.950,2521.0
3,2009,12,-2.0,19.0,5.451613,29.055914,-5.0,15.0,2.354839,24.303226,...,0.0,76.78,6.97,8.989,7.586,774,12.225,3.37,10.425,3390.0
4,2009,2,-6.0,18.0,6.964286,30.850529,-9.0,13.0,2.785714,24.322751,...,200.0,55.21,-4.32,9.296,7.559,799,12.589,3.87,11.100,1729.0

In [5]:
train_data.isnull().sum()

Year                                                                 0
Month                                                                0
Temp high (°C)min                                                    0
Temp high (°C)max                                                    0
Temp high (°C)mean                                                   0
Temp high (°C)var                                                    0
Temp avg (°C)min                                                     0
Temp avg (°C)max                                                     0
Temp avg (°C)mean                                                    0
Temp avg (°C)var                                                     0
Temp low (°C)min                                                     0
Temp low (°C)max                                                     0
Temp low (°C)mean                                                    0
Temp low (°C)var                                                     0
Dew Point high (°C)min                                               0
Dew Point high (°C)max                                               0
Dew Point high (°C)mean                                              0
Dew Point high (°C)var                                               0
Dew Point avg (°C)min                                                0
Dew Point avg (°C)max                                                0
Dew Point avg (°C)mean                                               0
Dew Point avg (°C)var                                                0
Dew Point low (°C)min                                                0
Dew Point low (°C)max                                                0
Dew Point low (°C)mean                                               0
Dew Point low (°C)var                                                0
Humidity_highmin                                                     0
Humidity_highmax                                                     0
Humidity_highmean                                                    0
Humidity_highvar                                                     0
                                                                    ..
Fog                                                                  0
Fog , Rain                                                           0
Fog , Rain , Snow                                                    0
Fog , Snow                                                           0
Other                                                                0
Rain                                                                 0
Rain , Snow                                                          0
Snow                                                                 0
Thunderstorm                                                         0
Event                                                                0
Federal Holiday                                                      0
Event_Yes_No                                                         0
Federal Holiday_Yes_No                                               0
Monthly Nominal GDP Index (inMillion$)                               0
Monthly Real GDP Index (inMillion$)                                  0
CPI                                                                  0
unemployment rate                                                    0
CommercialBankInterestRateonCreditCardPlans                          0
Finance Rate on Personal Loans at Commercial Banks, 24 Month Loan    0
Earnings or wages  in dollars per hour                               0
AdvertisingExpenses (in Thousand Dollars)                            0
Cotton Monthly Price - US cents per Pound(lbs)                       0
Change(in%)                                                          0
Average upland planted(million acres)                                0
Average upland harvested(million acres)                              0
yieldperharvested acre                                               0
Production (in  480-lb netweright in million bales)                  0
Mill use  (in  480-lb netweright in million bales)                   0
Exports                                                              0
WomenClothing_Sales                                                  0
Length: 104, dtype: int64

In [6]:
vals_to_replace = {'No':0, 'Yes':1}
train_data['Event_Yes_No'] = train_data['Event_Yes_No'].apply(lambda x: vals_to_replace[x])
train_data['Federal Holiday_Yes_No'] = train_data['Federal Holiday_Yes_No'].apply(lambda x: vals_to_replace[x])

## Models

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import r2_score
from sklearn.model_selection import KFold 
from sklearn.model_selection import cross_val_score

In [15]:
import lightgbm as lgb
from sklearn.model_selection import StratifiedKFold

In [8]:
X = train_data.copy().drop('WomenClothing_Sales', axis = 1)
Y = train_data[['WomenClothing_Sales']]
Y1 = train_data['Year']

In [11]:
trainX_fold, valX_fold, trainY_fold, valY_fold =  train_test_split(X, Y1, test_size=0.2, random_state=42, shuffle=False)


rf_model_cross_val  = RandomForestRegressor(min_samples_leaf = 3, n_estimators=100, max_features='sqrt') 
scores = cross_val_score(rf_model_cross_val, X, Y,  cv=5)
scores

# kf = KFold(n_splits=2)
# kf.get_n_splits(X_fold)
# print(kf) 
# KFold(n_splits=2, random_state=None, shuffle=False)

# for train_index, val_index in kf.split(X_fold):
#     X_train, X_val = X_fold[train_index], X_fold[val_index]
#     y_train, y_val = Y_fold[train_index], Y_fold[val_index]

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

array([-0.7892255 ,  0.32201074, -0.10397864,  0.27649355,  0.18747286])

In [ ]:
np.mean(scores)*100

In [ ]:
##################---------------------------------######################---------------------------------##################

In [9]:
trainX, valX, trainY, valY = train_test_split(X, Y, test_size=0.2, random_state=42, shuffle=True)

In [10]:
rf_model = RandomForestRegressor(min_samples_leaf = 3, n_estimators=100, max_features='sqrt')
rf_model.fit(trainX, trainY)

print(rf_model.feature_importances_)

[0.03948677 0.0260343  0.00247269 0.00540793 0.00593476 0.00686623
 0.00337137 0.00537296 0.00895141 0.00737592 0.01341895 0.00397693
 0.00592568 0.00448112 0.0074535  0.00853882 0.00386718 0.02126421
 0.00622072 0.00308186 0.00109017 0.0070323  0.00969104 0.00334633
 0.00351464 0.01584972 0.0024736  0.02085594 0.01725245 0.00294857
 0.00394727 0.00228515 0.0065868  0.00308103 0.006959   0.00091771
 0.01434018 0.00563093 0.00520056 0.00847754 0.01468926 0.00176343
 0.00317225 0.01140583 0.02680178 0.0042275  0.00151537 0.00336257
 0.01688886 0.00317441 0.00080484 0.         0.00306825 0.00472615
 0.00080157 0.         0.00677812 0.00596924 0.00220221 0.
 0.00787335 0.02500026 0.00546962 0.00591918 0.00599829 0.00636019
 0.00847452 0.0024916  0.00959156 0.00496548 0.00228355 0.00088635
 0.00924081 0.00507148 0.         0.00414207 0.         0.
 0.00678167 0.00303183 0.         0.00323064 0.         0.03006527
 0.00506022 0.00371415 0.00025185 0.06548445 0.05600527 0.0358032
 0.02805906 0.00306163 0.02303696 0.0604525  0.         0.00340698
 0.02749052 0.00689775 0.00100241 0.00359766 0.00166217 0.03304291
 0.05275672]

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

In [11]:
X_cols = X.columns
feature_imp_RFC = pd.DataFrame({"imp_features":rf_model.feature_importances_, "columns":X_cols})
#feature_imp_RFC.plot.bar(x="columns", y="imp_features")
feature_imp_RFC.sort_values(by = 'imp_features', ascending=False)

                                               columns  imp_features
87              Monthly Nominal GDP Index (inMillion$)      0.065484
93              Earnings or wages  in dollars per hour      0.060452
88                 Monthly Real GDP Index (inMillion$)      0.056005
102                                            Exports      0.052757
0                                                 Year      0.039487
89                                                 CPI      0.035803
101  Mill use  (in  480-lb netweright in million ba...      0.033043
83                                               Event      0.030065
90                                   unemployment rate      0.028059
96                                         Change(in%)      0.027491
44                             Sea Level Press avgmean      0.026802
1                                                Month      0.026034
61                              Visibility (km) lowvar      0.025000
92   Finance Rate on Personal Loans at Commercial B...      0.023037
17                              Dew Point high (°C)var      0.021264
27                                    Humidity_highmax      0.020856
28                                   Humidity_highmean      0.017252
48                             Sea Level Press lowmean      0.016889
25                               Dew Point low (°C)var      0.015850
40                            Sea Level Press highmean      0.014689
36                                    Humidity_lowmean      0.014340
10                                    Temp low (°C)min      0.013419
43                              Sea Level Press avgmax      0.011406
22                               Dew Point low (°C)min      0.009691
68                                 Wind (km/h) avgmean      0.009592
72                                Wind (km/h) highmean      0.009241
8                                    Temp avg (°C)mean      0.008951
15                              Dew Point high (°C)max      0.008539
39                             Sea Level Press highmax      0.008478
66                                  Wind (km/h) avgmin      0.008475
..                                                 ...           ...
33                                     Humidity_avgvar      0.003081
52                            Visibility (km) highmean      0.003068
91         CommercialBankInterestRateonCreditCardPlans      0.003062
79                                                Rain      0.003032
29                                    Humidity_highvar      0.002949
67                                  Wind (km/h) avgmax      0.002492
26                                    Humidity_highmin      0.002474
2                                    Temp high (°C)min      0.002473
31                                     Humidity_avgmax      0.002285
70                                 Wind (km/h) highmin      0.002284
58                              Visibility (km) lowmin      0.002202
41                             Sea Level Press highvar      0.001763
100  Production (in  480-lb netweright in million b...      0.001662
46                              Sea Level Press lowmin      0.001515
20                              Dew Point avg (°C)mean      0.001090
98             Average upland harvested(million acres)      0.001002
35                                     Humidity_lowmax      0.000918
71                                 Wind (km/h) highmax      0.000886
50                             Visibility (km) highmin      0.000805
54                              Visibility (km) avgmin      0.000802
86                              Federal Holiday_Yes_No      0.000252
94           AdvertisingExpenses (in Thousand Dollars)      0.000000
82                                        Thunderstorm      0.000000
80                                         Rain , Snow      0.000000
77                                          Fog , Snow      0.000000
76                                   Fog , Rain , Snow      0.000000
74                                                 Fog      0.000000
59                              Visibility (km) lowmax      0.000000
55                              Visibility (km) avgmax      0.000000
51                             Visibility (km) highmax      0.000000

[103 rows x 2 columns]

### RF Prediction

### MAPE = [(abs(actual-predicted))/abs(actual)]*100

In [23]:
y_pred = rf_model.predict(valX)

def mean_absolute_percentage_error(y_true, y_pred): 
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

In [24]:
mean_absolute_percentage_error(valY, y_pred)

29.991439380614548

### Selecting Only top 40% records

In [14]:
feature_imp_RFC = feature_imp_RFC.sort_values('imp_features', ascending=False)
top_40_features = feature_imp_RFC.iloc[0:41, 0:1].values

In [15]:
imp_columns = pd.DataFrame()
for i in top_40_features:
    for j in i:
        imp_columns[j] = X[j]

In [16]:
imp_columns.head()

,Monthly Nominal GDP Index (inMillion$),Earnings or wages in dollars per hour,Monthly Real GDP Index (inMillion$),Exports,Year,CPI,Mill use (in 480-lb netweright in million bales),Event,unemployment rate,Change(in%),...,Dew Point high (°C)min,Temp avg (°C)var,Dew Point avg (°C)var,Humidity_lowmin,Average upland planted(million acres),Temp high (°C)var,Other,Visibility (km) avgmean,Humidity_avgmean,Wind (km/h) lowvar
0,14421.752895,22.05,14407.053343,11.550,2009,233.402,4.17,0,7.8,4.02,...,-16.0,13.956989,28.356989,22.0,9.296,16.664516,21.0,14.000000,57.354839,35.066667
1,14596.605447,22.27,14595.393094,10.000,2009,238.380,3.37,1,10.0,4.29,...,1.0,14.582796,24.498925,32.0,8.989,20.064516,17.0,14.064516,69.354839,42.724731
2,14590.432252,22.44,14559.410173,9.950,2009,238.777,3.37,0,9.9,7.42,...,-2.0,5.889655,17.109195,32.0,8.989,8.202299,20.0,14.666667,66.600000,41.429885
3,14512.495301,22.38,14471.040844,10.425,2009,238.427,3.37,2,9.9,6.97,...,-14.0,24.303226,53.759140,23.0,8.989,29.055914,20.0,13.774194,61.741935,36.651613
4,14389.200466,22.22,14366.176571,11.100,2009,234.663,3.87,1,8.3,-4.32,...,-17.0,24.322751,41.432540,20.0,9.296,30.850529,22.0,15.178571,54.000000,47.253968

In [73]:
trainX1, valX1, trainY1, valY1 = train_test_split(imp_columns, Y, test_size=0.2, random_state=42, shuffle=True)

TypeError: Invalid parameters passed: {'val_size': 0.2}

In [18]:
gbm = GradientBoostingRegressor(loss='huber', learning_rate=0.001, min_samples_leaf=3, criterion='mae')
gbm.fit(trainX1, trainY1)

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GradientBoostingRegressor(alpha=0.9, criterion='mae', init=None,
             learning_rate=0.001, loss='huber', max_depth=3,
             max_features=None, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=3, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=100,
             n_iter_no_change=None, presort='auto', random_state=None,
             subsample=1.0, tol=0.0001, validation_fraction=0.1, verbose=0,
             warm_start=False)

In [19]:
X1_cols = imp_columns.columns
feature_imp_gbm = pd.DataFrame({"imp_features_gbm":rf_model.feature_importances_, "columns":X_cols})
feature_imp_gbm = feature_imp_gbm.sort_values(by = 'imp_features_gbm', ascending=False)
feature_imp_gbm

                                               columns  imp_features_gbm
87              Monthly Nominal GDP Index (inMillion$)          0.065484
93              Earnings or wages  in dollars per hour          0.060452
88                 Monthly Real GDP Index (inMillion$)          0.056005
102                                            Exports          0.052757
0                                                 Year          0.039487
89                                                 CPI          0.035803
101  Mill use  (in  480-lb netweright in million ba...          0.033043
83                                               Event          0.030065
90                                   unemployment rate          0.028059
96                                         Change(in%)          0.027491
44                             Sea Level Press avgmean          0.026802
1                                                Month          0.026034
61                              Visibility (km) lowvar          0.025000
92   Finance Rate on Personal Loans at Commercial B...          0.023037
17                              Dew Point high (°C)var          0.021264
27                                    Humidity_highmax          0.020856
28                                   Humidity_highmean          0.017252
48                             Sea Level Press lowmean          0.016889
25                               Dew Point low (°C)var          0.015850
40                            Sea Level Press highmean          0.014689
36                                    Humidity_lowmean          0.014340
10                                    Temp low (°C)min          0.013419
43                              Sea Level Press avgmax          0.011406
22                               Dew Point low (°C)min          0.009691
68                                 Wind (km/h) avgmean          0.009592
72                                Wind (km/h) highmean          0.009241
8                                    Temp avg (°C)mean          0.008951
15                              Dew Point high (°C)max          0.008539
39                             Sea Level Press highmax          0.008478
66                                  Wind (km/h) avgmin          0.008475
..                                                 ...               ...
33                                     Humidity_avgvar          0.003081
52                            Visibility (km) highmean          0.003068
91         CommercialBankInterestRateonCreditCardPlans          0.003062
79                                                Rain          0.003032
29                                    Humidity_highvar          0.002949
67                                  Wind (km/h) avgmax          0.002492
26                                    Humidity_highmin          0.002474
2                                    Temp high (°C)min          0.002473
31                                     Humidity_avgmax          0.002285
70                                 Wind (km/h) highmin          0.002284
58                              Visibility (km) lowmin          0.002202
41                             Sea Level Press highvar          0.001763
100  Production (in  480-lb netweright in million b...          0.001662
46                              Sea Level Press lowmin          0.001515
20                              Dew Point avg (°C)mean          0.001090
98             Average upland harvested(million acres)          0.001002
35                                     Humidity_lowmax          0.000918
71                                 Wind (km/h) highmax          0.000886
50                             Visibility (km) highmin          0.000805
54                              Visibility (km) avgmin          0.000802
86                              Federal Holiday_Yes_No          0.000252
94           AdvertisingExpenses (in Thousand Dollars)          0.000000
82                                        Thunderstorm          0.000000
80                                         Rain , Snow          0.000000
77                                          Fog , Snow          0.000000
76                                   Fog , Rain , Snow          0.000000
74                                                 Fog          0.000000
59                              Visibility (km) lowmax          0.000000
55                              Visibility (km) avgmax          0.000000
51                             Visibility (km) highmax          0.000000

[103 rows x 2 columns]

In [25]:
y_cap = gbm.predict(valX1)

mean_absolute_percentage_error(valY1, y_cap)

29.701110251566586

In [27]:
r2_score(valY1, y_cap)

-0.20046700044828514

In [57]:
from sklearn.model_selection import GridSearchCV

In [54]:
import time

In [64]:
parameters = {
    "loss":["ls", 'huber', 'lad'],
    "learning_rate": [0.001, 0.01, 0.025, 0.05],
    "max_depth":[3, 5, 8, 10, 12],
    "criterion": ["friedman_mse", 'mae'],
    "min_samples_leaf":[2, 3, 5, 7, 9], 
    "n_estimators":[10, 15, 20]
    }
start_time = time.time()

gbm_grid = GridSearchCV(gbm, parameters, cv=5, n_jobs=-1)
gbm_grid.fit(trainX1, trainY1)

print("time :", (time.time() - start_time))

112.33793115615845

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [65]:
gbm_grid.best_params_

{'criterion': 'friedman_mse',
 'learning_rate': 0.05,
 'loss': 'ls',
 'max_depth': 10,
 'min_samples_leaf': 5,
 'n_estimators': 20}

In [66]:
y_predictions = gbm_grid.predict(valX1)
mean_absolute_percentage_error(valY1, y_predictions)

30.041053676499065

In [71]:
gbm_with_best_params = GradientBoostingRegressor(criterion='friedman_mse', learning_rate=0.05,
                                                loss = 'ls', max_depth=10, min_samples_leaf=5, n_estimators=20)
gbm_with_best_params.fit(trainX1, trainY1)

y_predictions1 = gbm_with_best_params.predict(valX1)
mean_absolute_percentage_error(valY1, y_predictions1)

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

30.03999219652229